---
title: "Geist.digital"
subtitle: "Forschungsnahe Dienste & Ressourcen für Geisteswissenschaften im digitalen Zeitalter"
format: 
  html:
    page-layout: full
    css: ['assets/css/mystyle.css']
engine: knitr
lang: 'de'
---


# Beratung & Qualifizierung

## Forschungsdatenmanagement (FDM)

::: {.columns2}

Unter *Forschungsdaten* sind prinzipiell alle Arten von Materialien zu verstehen, die während einer wissenschaftlichen Tätigkeit entstehen, die entwickelt oder entdeckt werden und die zur Beantwortung einer Forschungsfrage beitragen. Die geisteswissenschaftliche Forschung zeichnet sich durch eine besondere Vielfalt ihrer Forschungsdaten aus. In den Geisteswissenschaften gehören hierzu beispielsweise literarische Texte oder Gebrauchstexte, die einzeln interpretiert oder als Korpus untersucht werden, materielle Kunst- und Kulturobjekte, digitalisierte historische Quellen, Audio- und Videoaufnahmen musikalischer oder anderer Performances sowie soziale Kontakte und räumliche und zeitliche Beziehungen zwischen historischen Persönlichkeiten oder literarischen Figuren. Die Aufgabe von Forschungsdatenmanagement ist es, die Forschenden beim Umgang mit ihren Forschungsdaten zu begleiten, mit dem Ziel, den Nutzen der entstehenden Daten für die eigene und für andere Forschung zu maximieren. 

Die Universitätsbibliothek unterstützt Sie im Umgang mit Ihren Forschungsdaten und sorgt für deren nachhaltige Erschließung und Aufbewahrung. Zu unseren Angeboten gehören unter anderem: 

* Lektorate von Drittmittelanträgen hinsichtlich FDM in den Geisteswissenschaften
* Beratungen und Workshops zur Dokumentation von Forschungsprozessen und nachhaltiger Datennutzung
* Beratungen und Workshops zu hilfreichen digitalen Tools für das FDM

:::

## Digitale Methoden und Kompetenzen

::: {.columns2}

Der Einsatz digitaler Methoden ist in den Geisteswissenschaften längst keine Besonderheit einzelner Subdisziplinen oder Forschender mehr. Computerunterstütztes Arbeiten und der problemorientierte Einsatz digitaler Werkzeuge sind ein integraler Bestandteil wissenschaftlicher Methoden- und Informationskompetenz. Dazu gehören beispielsweise die automatisierte Erhebung und formale Analyse großer Textmengen (Text- und Data-Mining, TDM), Programmierkenntnisse, das Annotieren und Auszeichnen von Texten, ein konzeptuelles Verständnis statistischer Modelle sowie praktische Handlungskompetenz im Umgang mit Daten.

Die Universitätsbibliothek berät und unterstützt Sie bei der Auswahl und Anwendung geeigneter digitaler Methoden und begleitet Sie bei deren Integration in Forschung und Lehre. Unser Angebot umfasst unter anderem:

* Beratung und Workshops zum Einsatz digitaler Forschungswerkzeuge für die Erstellung, Aufbereitung, Auswertung und Visualisierung von Daten und Metadaten
* Schulungen zur Vermittlung digitaler wissenschaftlicher Arbeitstechniken, etwa zur Bearbeitung geisteswissenschaftlicher Forschungsgegenstände mit Hilfe von Programmiersprachen (Python, R) oder zum Erstellen einer digitalen Edition mit Hilfe von Auszeichnungssprachen (z. B. TEI).
* Beratung und technische Unterstützung beim Text und Data Mining

:::


# Infrastruktur & Ressourcen

## Technische Infrastruktur

::: {.columns2}

Die Universitätsbibliothek versorgt Forschende aus den Geisteswissenschaften mit der nötigen technischen Infrastruktur zur Digitalisierung ihrer Forschung und Lehre. In Zusammenarbeit mit dem IT- & Medien Centrum (ITMC) sowie Partnerhochschulen in der Region stellen wir Ihnen Datenbanken, eine Rechner- und Serverinfrastruktur, digitale Mediengeräte und Expertise für die Einrichtung und den Betrieb spezifischer Software bereit. Unser Angebot umfasst unter anderem:

* Ausleihe und Einweisung in die Nutzung digitaler Mediengeräte wie beispielsweise 360-Grad-Kameras, Virtual-Reality-Brillen und 3D-Scanner
* Einrichtung und Betrieb von fachspezifischer Software über virtuelle Maschinen
* Betrieb eines JupyterHubs und einer Gitlab-Instanz für das kollaborative Arbeiten, Programmieren, Analysieren und Visualisieren mit Jupyter Notebooks
* Lizenzierung fachspezifischer Datenbanken, beispielsweise Korpusplattformen

:::

## Experimentelle Umgebungen

::: {.columns2}

Die Universitätsbibliothek betreibt zwei innovative und experimentelle Räume, in denen spielerisch gelernt, geforscht und kreativ gearbeitet wird, sowohl analog als auch digital. Ziel ist es, neue Formen des Lernens und Forschens zu erproben und den Austausch zwischen Studierenden, Lehrenden und Forschenden zu fördern. Beide Räume verstehen sich als offene Lernumgebungen, die Neugier wecken und den kreativen Umgang mit digitalen Technologien fördern sollen.

* Hybrid Learning Center (HyLeC) Makerspace: Der HyLeC-Makerspace bietet vielfältige Möglichkeiten zum (angeleiteten) Ausprobieren und Selbermachen, beispielsweise ein 3D-Körperscanner und ein Podcast- und Videostudio.

* Game Lab: Das Game Lab eröffnet einen kostenlosen Zugang zu Hardware und Software rund um das Thema Videospiele. Hier wird gespielt, entwickelt und über die kulturelle Bedeutung von Games und interaktiven Medien diskutiert.

:::


# Publikation & Sichtbarkeit

::: {.columns2}

Die Universitätsbibliothek unterstützt Sie umfassend dabei, Ihre Forschungs- und Lehrmaterialien in innovativen, offenen und digitalen Formaten zu veröffentlichen. Unser Ziel ist es, wissenschaftliche Ergebnisse im Sinne von Open Science und Open Education sichtbar, zugänglich und nachnutzbar zu machen.

Unsere Angebote umfassen:

* Beratung und Förderung von Open-Access-Publikationen (unter bestimmten Voraussetzungen können die Publikationskosten mitfinanziert werden)
* Publikation von digitalen Monographien und neuartigen, vernetzten, multimedialen Formaten auf unserer universitätseigenen Open-Access-Plattform *TUDObooks*
* Herausgabe von digitalen Zeitschriften auf unserer universitätseigenen Open-Access-Plattform *TUDOjournals*
* Archivierung und Veröffentlichung von Forschungsdaten auf unserem universitätseigenen Open-Access-Repositorium *TUDOdata*
* Beratung zur Erstellung und Veröffentlichung von Open Educational Resources (OER)

:::

# Archivierung & Bewahrung

::: {.columns2}

Das im Jahr 2012 gegründete Archiv der Technischen Universität Dortmund verwahrt Unterlagen zur Geschichte der im Jahr 1968 gegründeten Universität und ihrer Vorgängereinrichtungen. Darüber hinaus bewahrt und pflegt unser Archiv eine Reihe einzigartiger Sammlungen. 

Das Archiv wird als zentraler Partner für die kultur- und geisteswissenschaftliche Forschung ausgebaut. Die Sammlungen werden in den Katalog Plus integriert, sodass die einzelnen Sammlungsstücke in einem digitalen Lesesaal auffindbar, betrachtbar und vernetzt sein werden.

:::