---
title: "Geisteswissenschaften.digital"
subtitle: "Support & Ressourcen für Geistes- und Kulturwissenschaften im digitalen Zeitalter"
date: today
date-format: "long"
format: 
 revealjs:
  slide-number: true
  smaller: true
  scrollable: true
  header-logo: "_extensions/tudo-header/resources/img/logoTU.png"
  header-logo2: "_extensions/tudo-header/resources/img/logoUB.png"
  theme: [default, "_extensions/tudo-header/resources/css/custom.scss"]
  css: ["_extensions/tudo-header/resources/css/custom.css", "assets/css/mystyle.css"]
  self-contained: true
  embedded-resources: true
filters:
 - tudo-header
 - "assets/lua/pandoc-quotation.lua"
lang: "de"
editor_options: 
 chunk_output_type: console
execute:
 echo: false 
 warning: false
 message: false
 cache: false
bibliography: "./../literature/literature.yaml"
toc: false
toc-title: "Inhaltsverzeichnis"
toc-depth: 1
slide-level: 2
---

## Geisteswissenschaften.digital

**Support & Ressourcen für Geistes- und Kulturwissenschaften im digitalen Zeitalter** 

- Beratung & Qualifizierung 
- Technik & Library Labs 
- Publikation & Archivierung 

## Forschungsdatenmanagement (FDM)

**Forschungsdaten in den Geistes- und Kulturwissenschaften: vielfältig und 'messy'**

Texte, Editionen, Korpora, Digitalisate, AV-Medien, Objekte, Metadaten, Netzwerke u.v.m.

**FDM hilft** 
Strukturierter und nachhaltiger Umgang mit Daten in allen Projektphasen 

**Unsere Angebote**

- Beratung
- Antragslektorat
- Workshops & praxisnahe Trainings
- Unterstützung bei Veröffentlichung von Daten

## Digitale Methoden & Kompetenzen

**Digitale Methoden sind integraler Bestandteil moderner Geisteswissenschaften** 

Die Universitätsbibliothek berät und unterstützt Sie bei der Auswahl und Anwendung geeigneter digitaler Methoden, begleitet Sie bei deren Integration in Forschung und Lehre und vermittelt grundlegende Kompetenzen für ein modernes geistes- und kulturwissenschaftliches Studium.

**Unsere Angebote**

- Vermittlung von Data Literacy
- Einführung digitaler Werkzeuge
- Integration in Forschung & Lehre
- Technischer & rechtlicher Beratung zu TDM

## Beispiel Text und Data Mining

bla blab was ist text mining


## Technologie 

Die Universitätsbibliothek versorgt Forschende aus den Geistes- und Kulturwissenschaften mit der nötigen Technologie zur Digitalisierung ihrer Forschung und Lehre.

**Mediengeräte zum Verleih ** 360°-Kameras, Virtual-Reality-Brillen, Video- und Audiorekorder, 3D-Scanner, ... 

**Betrieb digitaler Infrastruktur**

- Virtuelle Maschinen
- JupyterHub & GitLab
- Lizenzierung von Datenbanken

## Library Labs

Die Universitätsbibliothek betreibt zwei innovative und experimentelle Räume, in denen spielerisch gelernt, geforscht und kreativ gearbeitet wird, sowohl analog als auch digital.

**Hybrid Learning Center (HyLeC)** 

Makerspace mit vielfältigen Möglichkeiten zum Ausprobieren und Selbermachen, beispielsweise mit einem 3D-Körperscanner und einem Podcast- und Videostudio

**Game Lab** 

Kostenfreier Zugang zu Hardware und Software rund um das Thema Videospiele


## Publikation & Sichtbarkeit

Die Universitätsbibliothek unterstützt Sie umfassend bei der Publikation Ihrer Forschungsergebnisse und Lehrmaterialien in innovativen, offenen und digitalen Formaten.

**Publikationsplattformen**

- Monographien und Tagungsbände open-access publizieren auf **TUDObooks**
- Zeitschriften open-access herausgeben auf **TUDOjournals**
- Wissenschaftlicher Arbeiten veröffentlichen auf **Eldorado**
- Forschungsdaten sicher speichern und publizieren auf **TUDOdata** 

**Weitere Unterstützung**

- Open-Access-Beratung
- Finanzierungsmöglichkeiten (auf Antrag)
- OER-Beratung

## Archivierung & Bewahrung

### Universitätsarchiv der TU Dortmund

Das im Jahr 2012 gegründete Archiv der Technischen Universität Dortmund verwahrt Unterlagen zur Geschichte der Universität und ihrer Vorgängereinrichtungen.

- Dokumente zur Universitätsgeschichte (seit 1968)
- Einzigartige Sondersammlungen

Das Archiv wird als zentrale Infrastruktur für die geistes- und kulturwissenschaftliche Forschung ausgebaut.

- Ausbau als Forschungsinfrastruktur
- Integration in den digitalen Lesesaal (Katalog Plus)

**Sie haben eine Sammlung?** Kontaktieren Sie uns für einen Austausch zu Möglichkeiten der Integration ins Archiv.

