---
title: "Geisteswissenschaften.digital"
subtitle: "Support & Ressourcen für Geistes- und Kulturwissenschaften im digitalen Zeitalter"
format: 
  # docx
  # html:
  dashboard:
    page-layout: full
    theme: cosmo
    orientation: rows
    expandable: true
    scrolling: true
    css: ['assets/css/mystyle.css','_extensions/tudo-header/resources/css/custom.css']
embed-resources: true
filters: ['assets/lua/pandoc-quotation.lua']
engine: knitr
lang: 'de'
bibliography: ['./../literature/literature.yaml']
---
Die Universitätsbibliothek begleitet und unterstützt den digitalen Wandel in Forschung und Lehre der Geistes- und Kulturwissenschaften. Hier finden Sie Support und Ressourcen für den Einsatz digitaler Methoden, die Vermittlung digitaler Kompetenzen und die Einrichtung von informationstechnologischer Infrastruktur. Unser Portfolio wird kontinuierlich erweitert. Wir freuen uns über Ihre Anfragen und Anregungen.

Dr. Daniel Jach \
Data Steward für Digital Humanities \
daniel.jach@tu-dortmund.de

<!-- # Beratung & Qualifizierung -->

## row {.fill}

::: {.card title="Forschungsdatenmanagement (FDM)" fill='true' height='500px'}

{{< iconify ix:data-management-filled  style="color: #83B818; margin-bottom: 25px;" width=150px >}} 

Unter *Forschungsdaten* sind prinzipiell alle Arten von Materialien zu verstehen, die während einer wissenschaftlichen Tätigkeit entstehen, entwickelt oder entdeckt werden und zur Beantwortung einer Forschungsfrage beitragen. Die geistes- und kulturwissenschaftliche Forschung zeichnet sich durch eine besondere Vielfalt ihrer Forschungsdaten aus. Hierzu gehören beispielsweise literarische Texte oder Gebrauchstexte, die einzeln interpretiert oder als Korpus untersucht werden, materielle Kunst- und Kulturobjekte, digitalisierte historische Quellen, Audio- und Videoaufnahmen musikalischer oder anderer Performances. Auch Daten zu sozialen Beziehungen sowie zu räumlichen und zeitlichen Kontakten zwischen historischen Persönlichkeiten oder literarischen Figuren können die Datengrundlage einer geistes- oder kulturwissenschaftlichen Untersuchung bilden. 

Das Forschungsdatenmanagement ermöglicht einen strukturierten Umgang mit Forschungsdaten, von der Erhebung über die Dokumentation bis hin zur Archivierung und Nachnutzung. Das Ziel besteht darin, den wissenschaftlichen Wert der entstehenden Daten für die eigene Forschung und die anderer Forschender zu maximieren.

Der Forschungsdatenservice der Universitätsbibliothek berät und begleitet Sie im Umgang mit Ihren Forschungsdaten und sorgt für deren nachhaltige Erschließung, Veröffentlichung und Aufbewahrung. Zu unseren Angeboten gehören unter anderem: 

* **Umfassende Beratung in allen Projektphasen** Kontaktieren Sie uns frühzeitig. Wir unterstützen Sie gern in allen Projektphasen, von der Konzeptionierung einer Idee über die Organisation und Verarbeitung von Forschungsdaten während des Projekts bis hin zur [FAIRen](https://forschungsdaten.info/themen/veroeffentlichen-und-archivieren/faire-daten/) Veröffentlichung und nachhaltigen Archivierung Ihrer Forschungsdaten.
* **Antragslektorat** Schicken Sie uns Ihren Entwurf für einen Drittmittelantrag. Wir sind mit den Anforderungen der Drittmittelgeber vertraut und kommentieren Ihren Text hinsichtlich FDM in den Geistes- und Kulturwissenschaften.
* **Beratung und Training für die Praxis** Gerne unterstützen wir Sie bei der Auswahl und Anwendung geeigneter Software für das Forschungsdatenmanagement. Unser Angebot reicht von einfacher Beratung für bestimmte Projekte bis hin zu praxisnahen Workshops zur gezielten Qualifizierung von Nachwuchsforschenden.

Weitere Informationen zu diesem Thema finden Sie auf der Website der zuständigen Abteilung. [{{< iconify streamline-sharp:link-share-2 >}}](https://fdm.tu-dortmund.de/)

:::

::: {.card title="Digitale Methoden und Kompetenzen" fill='true' height='500px'}

{{< iconify streamline:computer-pc-desktop-remix style="color: #83B818; margin-bottom: 25px;" width=150px >}}

Der Einsatz digitaler Methoden ist in den Geistes- und Kulturwissenschaften längst keine Besonderheit einzelner Subdisziplinen oder Forschender mehr. Computerunterstütztes Arbeiten und der problemorientierte Einsatz digitaler Werkzeuge sind ein integraler Bestandteil wissenschaftlicher Methoden- und Informationskompetenz. Dazu gehören beispielsweise die automatisierte Erhebung und formale Analyse großer Textmengen (Text- und Data-Mining, TDM), Programmierkenntnisse, das Annotieren und Auszeichnen von Texten, ein konzeptuelles Verständnis statistischer Modelle sowie praktische Handlungskompetenz im verantwortungsvollen Umgang mit Daten.

Die Universitätsbibliothek berät und unterstützt Sie bei der Auswahl und Anwendung geeigneter digitaler Methoden, begleitet Sie bei deren Integration in Forschung und Lehre und vermittelt grundlegende Kompetenzen für ein modernes geistes- und kulturwissenschaftliches Studium. Unser Angebot umfasst unter anderem:

* **Data Literacy im Fachkontext verankern** Wir bieten Schulungen zur Vermittlung digitaler wissenschaftlicher Arbeitstechniken, etwa zur Bearbeitung geistes- und kulturwissenschaftlicher Forschungsgegenstände mit Hilfe von Programmiersprachen (Python, R) oder zum Erstellen einer digitalen Edition mit Hilfe von Auszeichnungssprachen (z. B. TEI-XML).
* **Digitale Forschungswerkzeuge einführen** In der geistes- und kulturwissenschaftlichen Community hat sich ein umfangreiches Repertoire an digitalen Werkzeugen etabliert, das alle Phasen eines Forschungsprozesses unterstützt. Dazu gehören beispielsweise Programme zur automatischen Transkription von Gesprächen und zur Digitalisierung von Handschriften sowie Anwendungen zur Analyse von Textkorpora oder einzelnen Texten, zur Annotation und zur Edition digitaler Quellen. Wir beraten Sie gerne zu ausgewählten Werkzeugen und unterstützen Sie in Co-Teaching-Formaten bei der Einführung digitaler Forschungswerkzeuge in Ihre Lehre.
* **Text- und Data-Mining nutzen** Die Universitätsbibliothek verfügt über technische und rechtliche Expertise auf dem Gebiet des Text- und Data-Minings. Wir beraten und unterstützen Sie gern bei Forschungsvorhaben oder Lehrkonzepten, die diese Methodik nutzen. [{{< iconify streamline-sharp:link-share-2 >}}](https://ub.tu-dortmund.de/forschen-publizieren/publikationsunterstuetzung/text-and-data-mining-tdm/)

:::

<!-- # Digitale Infrastruktur & Library Labs -->

## row {.fill}

::: {.card title="Digitale Infrastruktur" fill='true' height='500px'}

{{< iconify streamline-plump:deepfake-technology-1-solid style="color: #83B818; margin-bottom: 25px;" width=150px >}} 

Die Universitätsbibliothek versorgt Forschende aus den Geistes- und Kulturwissenschaften mit der nötigen Technologie zur Digitalisierung ihrer Forschung und Lehre. In Zusammenarbeit mit dem IT- & Medien Centrum (ITMC) sowie Partnerinstitutionen in der Region stellen wir Ihnen Datenbanken, eine Rechner- und Serverinfrastruktur, digitale Mediengeräte und Expertise für die Einrichtung und den Betrieb von Software bereit. Unser Angebot umfasst unter anderem:

* **Digitale Mediengeräte ausleihen** Die Universitätsbibliothek verleiht high-end digitale Mediengeräte und steht Ihnen mit Expertise bei der Nutzung und anschließenden Datenverarbeitung zur Seite. Unser Depot umfasst beispielsweise 360-Grad-Kameras, Virtual-Reality-Brillen, Video- und Audiorekorder sowie 3D-Scanner. [{{< iconify streamline-sharp:link-share-2 >}}](https://hylec.tu-dortmund.de/)
* **Fachspezifische Software hosten** Für den zeitweisen Betrieb von Softwarelösungen mit kleinerem Nutzerkreis können einzelne Institute und Forschende die Einrichtung einer virtuellen Maschine beantragen, beispielsweise zur Verwendung fachspezifischer Analysesoftware in der Lehre oder die Pilotierung einer Eigenentwicklung.
* **Kollaborativ Programmieren** Für das kollaborative Programmieren stehen den Mitarbeitenden und Studierenden unserer Universität ein JupyterHub und eine GitLab-Instanz zur Verfügung. Gerne beraten und begleiten wir Sie bei der Nutzung sowie bei der Integration dieser Technologien in Forschung und Lehre. 
* **Projektwebseite einrichten** Über unsere GitLab-Instanz können Sie eine statische Website einrichten, um Ihr Projekt zu präsentieren. Dadurch wird Ihre Forschung sichtbarer und auch für eine breitere Öffentlichkeit zugänglich. Wir beraten Sie gerne bei der technischen Umsetzung.
* **Fachspezifische Datenbanken lizenzieren** Die Universitätsbibliothek übernimmt für Sie die Recherche und Lizenzierung von fachspezifischen Datenbanken, beispielsweise Korpusplattformen. Die Finanzierung muss aber in der Regel aus Fakultätsmitteln erfolgen.

:::

::: {.card title="Library Labs" fill='true' height='500px'}

{{< iconify streamline:ai-gaming-spark-solid style="color: #83B818; margin-bottom: 25px;" width=150px >}} 

Die Universitätsbibliothek betreibt zwei innovative und experimentelle Räume, in denen spielerisch gelernt, geforscht und kreativ gearbeitet wird, sowohl analog als auch digital. Ziel ist es, neue Formen des Lernens und Forschens zu erproben und den Austausch zwischen Studierenden, Lehrenden und Forschenden zu fördern. Beide Räume verstehen sich als offene Lernumgebungen, die Neugier wecken und den kreativen Umgang mit digitalen Technologien fördern sollen.

* **Hybrid Learning Center (HyLeC) Makerspace** Der HyLeC-Makerspace bietet vielfältige Möglichkeiten zum Ausprobieren und Selbermachen, beispielsweise einen 3D-Körperscanner und ein Podcast- und Videostudio. Unsere Mitarbeitenden leiten Sie bei der Verwendung gern an und bieten darüber hinaus ausführliche Workshops zum kreativen und wissenschaftlichen Arbeiten an. [{{< iconify streamline-sharp:link-share-2 >}}](https://hylec.tu-dortmund.de/)



* **Game Lab** Das Game Lab eröffnet einen kostenfreien Zugang zu Hardware und Software rund um das Thema Videospiele. Hier wird gespielt, entwickelt und über die kulturelle Bedeutung von Games und interaktiven Medien diskutiert. Das Game Lab wird derzeit vom Institut für American Studies betrieben und wird demnächst in die Universitätsbibliothek integriert. [{{< iconify streamline-sharp:link-share-2 >}}](https://islk.kuwi.tu-dortmund.de/gamestudies/) 

:::

<!-- # Publikation & Archivierung -->

## row {.fill}

::: {.card title="Publikation" fill='true' height='500px'}

{{< iconify glyphs:books-bold style="color: #83B818; margin-bottom: 25px;" width=150px >}} 

Die Universitätsbibliothek unterstützt Sie umfassend bei der Publikation Ihrer Forschungsergebnisse und Lehrmaterialien in innovativen, offenen und digitalen Formaten. Unser Ziel ist es, wissenschaftliche Ergebnisse im Sinne von Open Science und Open Education sichtbar, zugänglich und nachnutzbar zu machen. Unsere Angebote umfassen:

* **Open-Access publizieren** Auf unseren universitätseigenen Plattform *TUDObooks* [{{< iconify streamline-sharp:link-share-2 >}}](https://ub.tu-dortmund.de/forschen-publizieren/open-access/tudobooks/) und *Eldorado* [{{< iconify streamline-sharp:link-share-2 >}}](https://eldorado.tu-dortmund.de/home) bieten wir Ihnen die Möglichkeit, Ihre Forschungsergebnisse digital und open-access zu publizieren. Wir beraten Sie gerne zu den technischen Möglichkeiten und zum Publikationsprozess. Darüber hinaus unterstützen wir Sie bei externen Open-Access-Publikationen, beispielsweise bei der Auswahl reputabler Zeitschriften und bei Fragen zu den rechtlichen Rahmenbedingungen. Unter bestimmten Voraussetzungen ist auf Antrag auch die Übernahme von Publikationskosten möglich. Kontaktieren Sie uns hierzu frühzeitig. Weitere Informationen zu diesem Thema finden Sie auf der Website der zuständigen Abteilung. [{{< iconify streamline-sharp:link-share-2 >}}](https://ub.tu-dortmund.de/forschen-publizieren/open-access/)
* **Open-Access herausgeben** Auf unserer universitätseigenen Plattform *TUDOjournals* können Sie eine digitale Open-Access-Zeitschrift herausgeben. Wir beraten Sie gern zur Einrichtung und zum Betrieb einer Zeitschrift. [{{< iconify streamline-sharp:link-share-2 >}}](https://ub.tu-dortmund.de/forschen-publizieren/open-access/tudojournals/)
* **Forschungsdaten publizieren** Auf unserem universitätseigenen Repositorium *TUDOdata* können Sie Forschungsdaten nach dem erfolgreichen Abschluss Ihres Forschungsprojekts sicher und langfristig speichern sowie nach Bedarf veröffentlichen. [{{< iconify streamline-sharp:link-share-2 >}}](https://fdm.tu-dortmund.de/fdm-an-der-tu-dortmund/technische-unterstuetzung/tudodata/)
* **Open Educational Resources (OER) erstellen und publizieren** Gerne beraten wir Sie zu den grundlegenden Rahmenbedingungen und den ersten Schritten bei der Erstellung und Nutzung von Open Educational Resources. [{{< iconify streamline-sharp:link-share-2 >}}](https://digitale-lehre.tu-dortmund.de/open-educational-resources/)

:::

::: {.card title="Archivierung" fill='true' height='500px'}

{{< iconify fa-solid:archive style="color: #83B818; margin-bottom: 25px;" width=150px >}} 

Das im Jahr 2012 gegründete Archiv der Technischen Universität Dortmund verwahrt Unterlagen zur Geschichte der im Jahr 1968 gegründeten Universität und ihrer Vorgängereinrichtungen. Darüber hinaus bewahrt und pflegt unser Archiv eine Reihe einzigartiger Sammlungen. Das Archiv wird als zentrale Infrastruktur für die geistes- und kulturwissenschaftliche Forschung ausgebaut. Die Sammlungen werden in den Katalog Plus integriert, sodass die einzelnen Sammlungsstücke in einem digitalen Lesesaal auffindbar, betrachtbar und vernetzt sein werden. Kontaktieren Sie uns, wenn Sie eine Sammlung haben, anlegen und/oder in den entstehenden digitalen Lesesaal integrieren möchten. [{{< iconify streamline-sharp:link-share-2 >}}](https://ub.tu-dortmund.de/forschen-publizieren/universitaetsarchiv/)

:::